spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cloudread?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: cloudread
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: dummy@cloudread.com
    password: dummy-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    protocol: smtp

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    default-consumes-media-type: multipart/form-data
    default-produces-media-type: application/json
    path: /swagger-ui.html

openapi:
  title: CloudRead API
  version: v1.0.0
  description: Backend API for CloudRead project
  serverUrl: http://localhost:8080/

jwt:
  key: test123456789
  valid-duration: 3600   # giây
  issuer: "http://localhost:8080"
  next-step-valid-duration: 600   # giây
  refresh-duration: 86400         # giây

aws:
  s3:
    bucket-name: dummy-bucket
    region: ap-southeast-1
    access-key: dummy
    secret-key: dummy
